# Use the official Python image as the base image
FROM python:3.9-slim

# install psycopg2 dependencies
RUN apt-get update && \
    apt-get install -y libpq-dev gcc
# Install dependencies
RUN pip install psycopg2 requests pandas sqlalchemy

# Copy the Python script into the container
COPY load_data.py /app/load_data.py

# Set the working directory
WORKDIR /app

# Run the Python script
CMD ["python", "load_data.py"]